name: monai-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.6.0  # latest stable CPU-compatible version as of now
  - torchvision  # compatible with PyTorch 2.1.2
  - pytorch-lightning=2.5.5
  - monai=1.5.0
  - numpy=1.26.4
  - scipy
  - scikit-image
  - h5py
  - nibabel
  - pandas
  - matplotlib
  - tqdm
  - pytest
  - pip
  - pip:
      - tensorboard  # optional, useful for monitoring training
