name: monai-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.2  # latest stable CPU-compatible version as of now
  - torchvision=0.16.2  # compatible with PyTorch 2.1.2
  - pytorch-lightning=2.1.3
  - monai=1.3.0
  - numpy
  - scipy
  - scikit-image
  - h5py
  - nibabel
  - pandas
  - matplotlib
  - tqdm
  - pytest
  - pip
  - pip:
      - tensorboard  # optional, useful for monitoring training
